### ISSUE TITLE
Error when creating first note

### ISSUE THREAD

**Issue by josemiori** [dondominio/ddnotes#6]
Hello, I will try fixing and creating a pull  when resolved.... but may be someone can identify the issue faster...

27-Sep-2021 20:13:17 -0400]: <sfpjq3ir> DB Error: [1054] Unknown column 'New' in 'field list' (SQL Query: INSERT INTO `ddnotes` SET `parent_id` = 0, `user_id` = 1, `title` = "New", `mimetype` = "text/html", `content` = "", `file_size` = 0) in /var/www/roundcube/program/lib/Roundcube/rcube_db.php on line 543 (POST /rc/?_task=ddnotes&_action=new)

---------------
Ubuntu 20.04 php7.4
Roundcube Webmail 1.4.11
Installed plugins
Plugin	Version	License	Source
archive	3.4	GPLv3+	
calendar	0.0.7	GPL-3.0	Download
carddav	v4.2.0	GPL-2.0	Download
ddnotes	1.0.2	LGPL-3.0-only	Download
filesystem_attachments	1.0	GPLv3+	
jqueryui	1.12.0	GPLv3+	
libcalendaring	3.5.2	GPL-3.0-only	Download
libkolab	3.5.4	GPL-3.0-only	Download
managesieve	9.3	GPLv3+	
markasjunk	2.0	GPLv3+	
zipdownload	3.4	GPLv3+

**Comment by mcaif** [comment]
Hi @josemiori,

First of all, thank you for all the information related with this situation.

This error is caused due to `ANSI_QUOTES` mode on MySQL. The SQL sentences were using double quotes and they are identified as a column name instead of a value.

We have changed double quotes to single quotes on #7 . Please, download and try this new release and confirm if this situation is solved.

**Comment by josemiori** [comment]
Thanks,  I spent some time yesterday trying with no luck, I use to program assembler in the 90's this is too many quoting and escaping por me.  Cheers! It works like a charm now.
